name: Backport PR
on:
  pull_request:
    branches:
      - main
    types: ["closed", "labeled"]
    
jobs:
  backport-pr:
      name: backport-pr
      runs-on: ubuntu-latest
      # Only react to merged PRs for security reasons.
      # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target.
      if: |
        github.event.pull_request.merged == true
        && contains(github.event.pull_request.labels.*.name, 'backport')
        && (
          (github.event.action == 'labeled' && github.event.label.name == 'backport')
          || (github.event.action == 'closed')
        )
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: auto-cherry-pick
          # pinned to main branch commit where code was reviewed
          uses: xealth/cherry-pick-action@1d704ac0aa5e93c2c3e8db7876e7f02d0b89765a
          with:
            allowUserToSpecifyBranchViaLabel: 'true'
            labelPatternRequirement: 'v'
            userBranchPrefix: 'release/v'


